apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: keda-test
spec:
  podIdentity:
    provider: keda-sqs-role # or aws-eks when using IRSA
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: license-plate-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: license-plate-detection
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.ap-southeast-2.amazonaws.com/346337206895/licence_plate_queue
        queueLength: "5"
        awsRegion: ap-southeast-2